apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: FUNC_NAME
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: FUNC_NAME-func
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /FUNC_NAME
    tls: ""
  keepPrefix: true
  method: ""
  methods:
  - GET
  - POST
  prefix: /FUNC_NAME
  relativeurl: ""
